influx:
  image: tutum/influxdb
  container_name: influx
serializer:
  build: ./services/serializer/
  container_name: serializer
  links:
    - influx
  ports:
    - "3001:3001"
  environment:
    - SERVICE_HOST=0.0.0.0 
    - SERVICE_PORT=3001 
    - INFLUX_HOST=influx
#broker:
  # use the build declaration to connect to the broker code
  # use the link declaration to connect the broker to the serializer service
  # you will also need to use environment declarations
#sensor:
  # use the build declaration to connect to the sensor code
  # use the link declaration to connect the broker to the broker
frontend:
  build: ./frontend/
  container_name: frontend
  ports:
    - "3000:3000"




